### ISSUE TITLE
No anchor button styles in SCSS

### ISSUE THREAD

**Issue by colormono** [slavanga/baseguide#1]
Hi, with latest commit the .btn styles dissapear when I compile in SCSS.
I search for ".btn" classes in the hole folder and this appears only on compiled CSS files.
I saw in the previous version that this definitios was on _forms.scss; where are now?
Thanks for doing this, it's awesome! Best.

**Comment by slavanga** [comment]
Hi, thank you for using Baseguide. The button selector is no longer hardcoded and can be configured in the `_settings.scss` file.
https://github.com/slavanga/baseguide/blob/master/scss/baseguide/_settings.scss#L43

**Comment by colormono** [comment]
Ok, I was doing some testing. I noticed that the "anchor button" and "select" styles disappear when I add "bourbon" to the project. Don't know why yet. Any ideas?

**Comment by slavanga** [comment]
There is a conflict because the variables `$buttons-list` and `$inputs-list` already exist in bourbon. If you import bourbon after Baseguide everything should work.

``` scss```
@import 'baseguide';
@import 'bourbon';
```

I will probably rename those variables to avoid this in the future.
Thank you for reporting!

**Comment by colormono** [comment]
Yes, now works great. Thanks again, as I said before baseguide rocks! Best.
