### ISSUE TITLE
modular-scale, $size: $font-size-base ?

### ISSUE THREAD

**Issue by KasperAndersson** [slavanga/baseguide#13]
https://github.com/slavanga/baseguide/blob/056f73997171d276cd8389c9568ab9b6a4a86a52/scss/baseguide/01-tools/_functions.scss#L20

Should `$size` in the updated `modular-scale` function, be equal to `$font-size-base`, for backwards compability?

**Comment by slavanga** [comment]
The change was made in v4.0.0 which is a major release that doesn't need to be backwards compatible. But in this case it's very useful to add a default value.

If you submit a pull request I will happiliy merge it 👍
