### ISSUE TITLE
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

### ISSUE THREAD

**Issue by KasperAndersson** [slavanga/baseguide#16]
More information https://sass-lang.com/documentation/breaking-changes/slash-div

**Comment by slavanga** [comment]
Supporting Dart Sass will be a breaking change (new major version).
If someone finds the time to do a PR I will review and release it.

**Comment by W4ldgeist** [comment]
We went through that in our fork of base guide using: https://www.sass-lang.com/documentation/cli/migrator it's a one line command and then all is done :)

**Comment by slavanga** [comment]
The build process has to be adjusted too, which I already did on the outdated [v5-dev branch](https://github.com/slavanga/baseguide/tree/v5-dev).
